version: '2'
services:
    suividesdevisbeta-app:
        image: suividesdevisbeta
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://suividesdevisbeta-postgresql:5432/SuiviDesDevisBeta
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    suividesdevisbeta-postgresql:
        extends:
            file: postgresql.yml
            service: suividesdevisbeta-postgresql
