version: '2'
services:
    suividesdevisbeta-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/SuiviDesDevisBeta/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=SuiviDesDevisBeta
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
